# Project: Project6
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = HelloWordConsoleApp.o ../NewBie/Tim_So_Nguyen_Dau_Tien_Ko_XuatHien_Array.o
LINKOBJ  = HelloWordConsoleApp.o ../NewBie/Tim_So_Nguyen_Dau_Tien_Ko_XuatHien_Array.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = HelloWord.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

HelloWordConsoleApp.o: HelloWordConsoleApp.cpp
	$(CPP) -c HelloWordConsoleApp.cpp -o HelloWordConsoleApp.o $(CXXFLAGS)

../NewBie/Tim_So_Nguyen_Dau_Tien_Ko_XuatHien_Array.o: ../NewBie/Tim_So_Nguyen_Dau_Tien_Ko_XuatHien_Array.cpp
	$(CPP) -c ../NewBie/Tim_So_Nguyen_Dau_Tien_Ko_XuatHien_Array.cpp -o ../NewBie/Tim_So_Nguyen_Dau_Tien_Ko_XuatHien_Array.o $(CXXFLAGS)
